"use client";
import { FormEvent, useMemo, useState } from "react";
import { Footer } from "@/components/Footer";
import { SecurityBanner } from "@/components/SecurityBanner";
import { formatPaise, parseRupeesToPaise, splitIntoChunks } from "@/lib/money";
import { estimateStandardMdr } from "@/lib/rules";
import { encodeSession, PaymentSessionV1, SESSION_TTL_MS } from "@/lib/session";
import { Merchant, parseMerchantUpiQr, validateMerchant } from "@/lib/upi";

export default function CreatePage() {
 const [pa,setPa]=useState(""); const [pn,setPn]=useState(""); const [amount,setAmount]=useState(""); const [max,setMax]=useState("2000"); const [category,setCategory]=useState("standard"); const [qr,setQr]=useState(""); const [error,setError]=useState(""); const [dynamic,setDynamic]=useState(false);
 const plan=useMemo(()=>{try{return splitIntoChunks(parseRupeesToPaise(amount),parseRupeesToPaise(max));}catch{return [];}},[amount,max]);
 function importQr(){try{const r=parseMerchantUpiQr(qr);setPa(r.merchant.pa);setPn(r.merchant.pn);setDynamic(r.dynamic);setError("");}catch(e){setError(e instanceof Error?e.message:"Invalid QR");}}
 function submit(e:FormEvent){e.preventDefault();try{const merchant:Merchant=validateMerchant({pa,pn,source:qr?"merchant_qr":"manual"});const totalPaise=parseRupeesToPaise(amount);const chunksPaise=splitIntoChunks(totalPaise,parseRupeesToPaise(max));const now=Date.now();const s:PaymentSessionV1={version:1,merchant,invoice:{totalPaise},chunksPaise,createdAt:now,expiresAt:now+SESSION_TTL_MS,sessionId:crypto.randomUUID()};window.location.assign(`/s/${encodeSession(s)}`);}catch(x){setError(x instanceof Error?x.message:"Payment request could not be safely generated.");}}
 return <main className="shell compact"><header><a className="brand" href="/">mdr-ama<span>™</span></a><p>create a partial-payment session</p></header><SecurityBanner/><form className="card" onSubmit={submit}><h1>Set up the bill</h1><p className="muted">Confirm the merchant details before generating a session.</p><label>Import a merchant UPI QR <span>(paste QR contents)</span><textarea value={qr} onChange={e=>setQr(e.target.value)} placeholder="upi://pay?pa=merchant@upi&pn=Merchant"/><button className="secondary" type="button" onClick={importQr}>Read merchant QR</button></label>{dynamic&&<p className="warning">This appears to include a fixed amount or transaction reference. Use the merchant&apos;s normal/static QR if possible.</p>}<div className="fields"><label>Merchant UPI ID<input required value={pa} onChange={e=>setPa(e.target.value)} placeholder="merchant@upi"/></label><label>Merchant name<input required value={pn} onChange={e=>setPn(e.target.value)} placeholder="Sharma Stores"/></label></div><div className="fields"><label>Bill amount (₹)<input required inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="8750.00"/></label><label>Maximum payment step (₹)<input required inputMode="decimal" value={max} onChange={e=>setMax(e.target.value)}/></label></div><label>Merchant classification<select value={category} onChange={e=>setCategory(e.target.value)}><option value="standard">Standard P2M</option><option value="p2pm">P2PM / small merchant</option><option value="special">Special sector / capital markets</option><option value="unknown">Unknown</option></select></label>{category==="standard"&&plan.length>0&&<p className="estimate">{estimateStandardMdr(parseRupeesToPaise(amount))}</p>}{category!=="standard"&&<p className="estimate">Classification-specific rules may apply. Verify with your acquirer; no standard MDR estimate is shown.</p>}<section className="plan"><div><h2>Payment plan</h2><span>{plan.length} steps</span></div>{plan.map((chunk,i)=><p key={i}><span>{i+1}</span>{formatPaise(chunk)}</p>)}</section>{error&&<p role="alert" className="error">{error}</p>}<p className="fineprint">MDR-ama creates separate partial-payment requests. Actual MDR treatment is determined by your acquiring bank, payment provider and applicable rules.</p><button className="button" type="submit">Create master QR <span>→</span></button></form><Footer/></main>;
}
