"use client";
import { useParams } from "next/navigation";
import { useEffect, useState } from "react";
import QRCode from "qrcode";
import { Footer } from "@/components/Footer";
import { SecurityBanner } from "@/components/SecurityBanner";
import { formatPaise } from "@/lib/money";
import { decodeSession, PaymentSessionV1 } from "@/lib/session";
import { buildUpiUri, createAttemptReference } from "@/lib/upi";

type Progress = { index:number; completed:boolean[]; refs:string[] };
export default function SessionPage(){const {payload}=useParams<{payload:string}>();const [session,setSession]=useState<PaymentSessionV1>();const [error,setError]=useState("");const [started,setStarted]=useState(false);const [progress,setProgress]=useState<Progress>();const [qr,setQr]=useState("");
useEffect(()=>{try{const s=decodeSession(payload);setSession(s);const key=`mdr-ama:${s.sessionId}`;const old=localStorage.getItem(key);setProgress(old?JSON.parse(old):{index:0,completed:s.chunksPaise.map(()=>false),refs:s.chunksPaise.map(()=>"")});}catch(e){setError(e instanceof Error?e.message:"This payment session could not be safely decoded. Ask the merchant to create a new one.");}},[payload]);
function save(next:Progress){if(session){localStorage.setItem(`mdr-ama:${session.sessionId}`,JSON.stringify(next));setProgress(next);}}
const step=progress?.index??0;const done=progress?.completed.every(Boolean);const uri=session&&progress?buildUpiUri(session.merchant,session.chunksPaise[step],step,session.chunksPaise.length,progress.refs[step]||createAttemptReference()):"";
useEffect(()=>{if(uri) QRCode.toDataURL(uri,{margin:1,width:240}).then(setQr);},[uri]);
if(error)return <main className="shell compact"><header><a className="brand" href="/">mdr-ama™</a></header><section className="card error"><h1>Session unavailable</h1><p>{error}</p></section><Footer/></main>; if(!session||!progress)return <main className="shell compact">Loading session…</main>;
if(done)return <main className="shell compact"><header><a className="brand" href="/">mdr-ama™</a></header><section className="card"><p className="eyebrow">Session complete</p><h1>All payment steps marked completed</h1><p className="total">{formatPaise(session.invoice.totalPaise)} total</p><p>{session.chunksPaise.length} payment attempts marked completed by payer.</p><p className="warning"><strong>Important:</strong> MDR-ama has not independently verified settlement. The merchant must confirm the full amount in the bank, UPI app or soundbox.</p><a className="button" href="/">Done</a></section><Footer/></main>;
const s=session;const p=progress;const current=s.chunksPaise[step];function launch(){const refs=[...p.refs];if(!refs[step])refs[step]=createAttemptReference();save({...p,refs});window.location.href=buildUpiUri(s.merchant,current,step,s.chunksPaise.length,refs[step]);} function complete(){const completed=[...p.completed];completed[step]=true;save({...p,completed});} function retry(){const refs=[...p.refs];refs[step]=createAttemptReference();save({...p,refs});}
if(!started)return <main className="shell compact"><header><a className="brand" href="/">mdr-ama™</a></header><SecurityBanner/><section className="card"><p className="eyebrow">Payment session</p><h1>Pay {session.merchant.pn}</h1><p className="total">{formatPaise(session.invoice.totalPaise)}</p><p>{session.chunksPaise.length} separate UPI payments to <strong>{session.merchant.pa}</strong>.</p><label className="check"><input type="checkbox" onChange={e=>e.target.checked&&setStarted(true)}/> I understand that each payment is separate and requires separate authorisation.</label></section><Footer/></main>;
return <main className="shell compact"><header><a className="brand" href="/">mdr-ama™</a><p>Payment {step+1} of {session.chunksPaise.length}</p></header><SecurityBanner/><section className="card"><p className="eyebrow">Separate payment {step+1} of {session.chunksPaise.length}</p><h1>{formatPaise(current)}</h1><p className="muted">Remaining after this: {formatPaise(session.invoice.totalPaise-session.chunksPaise.slice(0,step+1).reduce((a,b)=>a+b,0))}</p><hr/><h2>{session.merchant.pn}</h2><p>{session.merchant.pa}</p><button className="button" onClick={launch}>Pay {formatPaise(current)} with UPI <span>→</span></button><p className="warning">Verify the payee name inside your UPI app before entering your PIN.</p><details><summary>Did the UPI app not open?</summary><p>No compatible UPI app opened. Verify/copy the payee and amount or use another device to scan the current payment QR.</p><button className="secondary" onClick={()=>navigator.clipboard.writeText(session.merchant.pa)}>Copy UPI ID</button>{qr&&<img className="qr" src={qr} alt={`UPI QR for ${formatPaise(current)}`}/>}</details><hr/><p>Welcome back. Did you complete the {formatPaise(current)} payment?</p><button className="button" onClick={complete}>Yes, I completed it</button><button className="secondary" onClick={retry}>Retry with a new reference</button><p className="fineprint">Selecting completion stores only a local, payer-reported state. It is not a settlement confirmation.</p></section><Footer/></main>;}
