"use client";

import Link from "next/link";
import { motion, useReducedMotion } from "framer-motion";
import { ArrowUpRight, CheckCircle2, QrCode, ShieldCheck, Smartphone } from "lucide-react";
import { Footer } from "./Footer";
import { SecurityBanner } from "./SecurityBanner";

const steps = [[QrCode, "Set the bill", "Confirm the merchant and split the amount precisely."], [Smartphone, "Share one QR", "One scan opens the guided payment session."], [CheckCircle2, "Pay deliberately", "Each UPI request is separately reviewed and approved."]];
export function Landing(){const reduce=useReducedMotion();const enter={hidden:{opacity:0,y:reduce?0:20},show:{opacity:1,y:0}};return <main className="shell"><header className="site-header"><Link className="brand" href="/">mdr-ama<span>™</span></Link><nav><Link href="/rules">Rules</Link><Link href="/account">Account</Link><Link className="nav-cta" href="/create">Create session</Link></nav></header><section className="hero new-hero"><motion.div initial="hidden" animate="show" transition={{duration:.5}} variants={enter}><p className="eyebrow">One bill, clearly orchestrated</p><h1>UPI payments,<br/><em>without</em> the chaos.</h1><p className="lead">Create a private, guided partial-payment session from one master QR. MDR-ama never touches money, PINs, or bank credentials.</p><div className="hero-actions"><Link className="button" href="/create">Create a master QR <ArrowUpRight size={18}/></Link><Link className="text-link" href="/rules">See the guardrails</Link></div></motion.div><motion.div className="hero-orb" initial={{opacity:0,scale:.88}} animate={{opacity:1,scale:1}} transition={{delay:.18,duration:.6,type:"spring"}}><div className="orb-inner"><QrCode size={84}/><span>ONE SCAN<br/>THREE STEPS</span></div></motion.div></section><SecurityBanner/><motion.section className="grid feature-grid" initial="hidden" whileInView="show" viewport={{once:true,amount:.25}} transition={{staggerChildren:.11}}>{steps.map(([Icon,title,text],index)=><motion.article key={title as string} variants={enter}><span className="step-number">0{index+1}</span><Icon size={25}/><h2>{title as string}</h2><p>{text as string}</p></motion.article>)}</motion.section><section className="trust-line"><ShieldCheck size={19}/><span>No payment processing. No claimed settlement. No customer MDR surcharge.</span></section><Footer/></main>}
